mysql:
    build: ./mysql
    ports:
        - "3306:3306"
    volumes:
        - "/data/mysql:/var/lib/mysql"
    environment:
        MYSQL_ROOT_PASSWORD: 123456
    #redis:
        #build: ./redis
        #ports:
            #- "6379:6379"

php:
    build: ./php
    ports:
        - "9000:9000"
    links:
        - "mysql"
        #- "redis"
    volumes:
        - "/data/sites:/usr/share/nginx/html"

nginx:
    build: ./nginx
    ports:
        - "80:80"
    links:
        - "php"
    volumes:
        - "/data/sites:/usr/share/nginx/html"