services:
  # PHP-FPM 處理器 (共用)
  php-fpm:
    #image: php:${PHP_VERSION}
    build:
      context: ./php
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ${PROJECTS_ROOT}:/var/www/html
    networks:
      - app_net

  # Nginx 服務獨立運作 (作為主要 Web Server, Port 80)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ${PROJECTS_ROOT}:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/header.html:/var/www/html/header.html
      - ./nginx/footer.html:/var/www/html/footer.html
      - ./nginx/.autoindex.css:/var/www/html/.autoindex.css
      - ./nginx/.autoindex.js:/var/www/html/.autoindex.js
    # depends_on:
    #   - php-fpm
    networks:
      - app_net

  # Apache - 獨立運作 (Port 8080)
  apache:
    image: httpd:2.4-alpine
    ports:
      - "8080:80"
    volumes:
      - ${PROJECTS_ROOT}:/var/www/html
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - app_net
  
  # 動態切換 MySQL / MariaDB 資料庫
  mysql:
    image: ${DB_IMAGE}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ${DATABASE_ROOT}:/var/lib/mysql
    networks:
      - app_net

  # Portainer (Web 管理界面)
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    # image: portainer/portainer-ce:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9443:9443"

  # # 自訂 Apache2
  # apache:
  #   build: ./apache
  #   container_name: my_apache
  #   networks:
  #     - app_net
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - php
  #     - mysql
  #   volumes:
  #     - "/data/sites:/usr/local/apache2/htdocs"

  # # 自訂 nginx  
  # nginx:
  #   build: ./nginx
  #   container_name: my_nginx
  #   networks:
  #     - app_net
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - php
  #     - mysql
  #   volumes:
  #     - "/data/sites:/usr/share/nginx/html"
  # php:
  #   build: ./php
  #   container_name: my_php
  #   networks:
  #     - app_net
  #   ports:
  #     - "9000:9000"
  #   extra_hosts:
  #     - "localhost:172.88.2.10"
  #   # networks:
  #   #   - frontend
  #   # links:
  #   #   - "mysql"
  #     #- "redis"
  #   volumes:
  #     - "/data/sites:/usr/share/nginx/html"
  #     - "/data/sites:/usr/local/apache2/htdocs"
  
  # # 自訂 MySQL
  # mysql:
  #   build: ./mysql
  #   container_name: my_mysql
  #   networks:
  #     - app_net
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - "/data/mysql:/var/lib/mysql"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456
  
  # 自訂 portainer
  # portainer:
  #   container_name: portainer
  #   image: portainer/portainer-ce:lts
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data
  #   ports:
  #     - 9443:9443

  # mongo:
  #   image: mongo
  #   restart: always
  #   container_name: my_mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: robot
  #     MONGO_INITDB_ROOT_PASSWORD: robot
  #   networks:
  #     app_net:
  #       ipv4_address: 172.88.2.13
  #   ports:
  #     - "27017:27017"
  #   # volumes:
  #   #   - "/data/db:/data/db"
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   container_name: my_mongo_express
  #   networks:
  #     app_net:
  #       ipv4_address: 172.88.2.14
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - mongo
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: robot
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: robot
  #     ME_CONFIG_MONGODB_SERVER: 172.88.2.13
    #redis:
      #build: ./redis
      #ports:
        #- "6379:6379"
# networks:
#   frontend: 
#     driver: bridge

volumes:
  mysql_data:
    name: mysql_data
  portainer_data:
    name: portainer_data

networks:
  app_net:
    driver: bridge