version: "3"
services:
  apache:
    build: ./apache
    container_name: my_apache
    networks:
      app_net:
        ipv4_address: 172.88.2.9
    ports:
      - "8080:80"
    depends_on:
      - php
      - mysql
    volumes:
      - "/data/sites:/usr/local/apache2/htdocs"
  nginx:
    build: ./nginx
    container_name: my_nginx
    networks:
      app_net:
        ipv4_address: 172.88.2.10
    ports:
      - "80:80"
    depends_on:
      - php
      - mysql
    volumes:
      - "/data/sites:/usr/share/nginx/html"
  php:
    build: ./php
    container_name: my_php
    networks:
      app_net:
        ipv4_address: 172.88.2.11
    ports:
      - "9000:9000"
    extra_hosts:
      - "localhost:172.88.2.10"
    # networks:
    #   - frontend
    # links:
    #   - "mysql"
      #- "redis"
    volumes:
      - "/data/sites:/usr/share/nginx/html"
      - "/data/sites:/usr/local/apache2/htdocs"
  mysql:
    build: ./mysql
    container_name: my_mysql
    networks:
      app_net:
        ipv4_address: 172.88.2.12
    ports:
      - "3306:3306"
    volumes:
      - "/data/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  mongo:
    image: mongo
    restart: always
    container_name: my_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: robot
      MONGO_INITDB_ROOT_PASSWORD: robot
    networks:
      app_net:
        ipv4_address: 172.88.2.13
    ports:
      - "27017:27017"
    # volumes:
    #   - "/data/db:/data/db"
  mongo-express:
    image: mongo-express
    restart: always
    container_name: my_mongo_express
    networks:
      app_net:
        ipv4_address: 172.88.2.14
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: robot
      ME_CONFIG_MONGODB_ADMINPASSWORD: robot
      ME_CONFIG_MONGODB_SERVER: 172.88.2.13
    #redis:
      #build: ./redis
      #ports:
        #- "6379:6379"
# networks:
#   frontend: 
#     driver: bridge
networks:
  app_net:
      ipam:
        driver: default
        config:
          - subnet: "172.88.2.0/24"
