server {
    listen 80;
    root /var/www/html;
    index index.php index.html index.htm;

    # 顯示目錄清單(⭐ 只處理 root directory listing)
    location / {
        fancyindex on;
        fancyindex_localtime on;
        fancyindex_exact_size off;

        try_files $uri $uri/ =404;

        # 可選：美化
        # fancyindex_header "/fancy_header.html";
        # fancyindex_footer "/fancy_footer.html";

        # autoindex on; # 顯示目錄列表
        # autoindex_exact_size off;
        # autoindex_localtime on;
        # try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP handler
    location ~ \.php$ {
        fastcgi_pass php-fpm:9000;
        # fastcgi_index index.php;
        include fastcgi_params;
        # 確保這裡的 root 路徑是 PHP-FPM 容器內的路徑
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        try_files $uri =404;
    }

    # 1. 處理 CI4 專案 (假設路徑為 /bestdoctor)
    location /bestdoctor {
        # 這是 CI4 路由的關鍵：如果檔案不存在，就導向該目錄下的 index.php
        try_files $uri $uri/ /bestdoctor/index.php$is_args$args;
    }

    location /icd_laravel {
        # 這是 CI4 路由的關鍵：如果檔案不存在，就導向該目錄下的 index.php
        try_files $uri $uri/ /icd_laravel/index.php$is_args$args;
    }
    
    # Deny access to hidden files (like .htaccess or .env)
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}