server {
    listen 80;
    root /var/www/html;
    index index.php index.html;

    location /stub_status {
        stub_status on;
        access_log off;
    }

    # 1. 處理 CI4 專案 (假設路徑為 /bestdoctor)
    location /bestdoctor {
        # 這是 CI4 路由的關鍵：如果檔案不存在，就導向該目錄下的 index.php
        try_files $uri $uri/ /bestdoctor/index.php$is_args$args;
    }

    location /icd_laravel {
        # 這是 CI4 路由的關鍵：如果檔案不存在，就導向該目錄下的 index.php
        try_files $uri $uri/ /icd_laravel/index.php$is_args$args;
    }

    # 顯示目錄清單
    location / {
        autoindex on; # 顯示目錄列表
        autoindex_exact_size off;
        autoindex_format html;
        autoindex_localtime on;

        # 可選：美化
        add_before_body /header.html;
        add_after_body /footer.html;

        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php-fpm:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        # 確保這裡的 root 路徑是 PHP-FPM 容器內的路徑
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Deny access to hidden files (like .htaccess or .env)
    location ~ /\.ht {
        deny all;
    }
}