FROM php:7.1-fpm

ADD php.ini /usr/local/etc/php/php.ini
ADD php-fpm.conf /usr/local/etc/php-fpm.conf

EXPOSE 9000

RUN apt-get update -y && apt-get install -y libpng-dev
#COPY redis.tgz /home/redis.tgz
RUN docker-php-ext-install gd \
 && docker-php-ext-install pdo_mysql \
 && docker-php-ext-install mysqli

#RUN docker-php-ext-install gd \
#   && docker-php-ext-install pdo_mysql \
#   && pecl install /home/redis.tgz && echo "extension=redis.so" > /usr/local/etc/php/conf.d/redis.ini
#ADD composer.phar /usr/local/bin/composer
#RUN chmod 755 /usr/local/bin/composer

#WORKDIR /opt
#RUN usermod -u 1000 www-data

#VOLUME ["/opt"]
